export default function AboutInfo() {
    return (
        <div className="container border-bottom pb-4 min-vh-99 d-flex flex-column align-items-center justify-content-center">
            <div className="content fs-5" style={{ color: "#ffffff" }}>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu ultrices vitae auctor eu augue. Magna fringilla urna porttitor rhoncus dolor. Varius morbi enim nunc faucibus a. Integer quis auctor elit sed vulputate mi sit amet. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Blandit aliquam etiam erat velit. Turpis tincidunt id aliquet risus feugiat in ante metus dictum. Purus faucibus ornare suspendisse sed nisi lacus. Ut aliquam purus sit amet luctus. At auctor urna nunc id cursus metus aliquam eleifend mi. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Consequat interdum varius sit amet mattis vulputate enim nulla.</p>
                <p>Consectetur a erat nam at lectus urna duis. Quis auctor elit sed vulputate mi sit amet mauris commodo. Bibendum enim facilisis gravida neque convallis a. Nulla pellentesque dignissim enim sit amet venenatis urna. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Nunc eget lorem dolor sed. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Donec adipiscing tristique risus nec feugiat in fermentum. Ligula ullamcorper malesuada proin libero nunc consequat. Vestibulum lectus mauris ultrices eros in cursus turpis. Mi ipsum faucibus vitae aliquet. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Consequat mauris nunc congue nisi vitae. Aliquam ut porttitor leo a diam sollicitudin tempor. Duis at consectetur lorem donec massa sapien. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Ipsum nunc aliquet bibendum enim. Eget velit aliquet sagittis id consectetur purus ut.</p>
                <p>Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Aliquam purus sit amet luctus. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Mollis nunc sed id semper risus in hendrerit. Pharetra pharetra massa massa ultricies mi. Id aliquet lectus proin nibh nisl. Varius morbi enim nunc faucibus a pellentesque sit amet. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Condimentum mattis pellentesque id nibh tortor id. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget nullam. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Fermentum leo vel orci porta. Adipiscing diam donec adipiscing tristique risus nec feugiat in. Odio morbi quis commodo odio aenean sed. Ut tortor pretium viverra suspendisse potenti nullam ac.</p>
                <p>Scelerisque eleifend donec pretium vulputate sapien nec sagittis. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Justo eget magna fermentum iaculis eu non diam phasellus vestibulum. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Enim nulla aliquet porttitor lacus luctus accumsan tortor. In hendrerit gravida rutrum quisque non. Ut sem viverra aliquet eget. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Habitant morbi tristique senectus et netus et malesuada fames ac. Tristique nulla aliquet enim tortor at auctor urna nunc. Ut eu sem integer vitae. Convallis posuere morbi leo urna molestie at. Dolor purus non enim praesent elementum. Proin sed libero enim sed faucibus turpis.</p>
                <p>Velit aliquet sagittis id consectetur purus ut. Et netus et malesuada fames ac turpis. Duis at consectetur lorem donec massa sapien faucibus et molestie. Iaculis nunc sed augue lacus viverra vitae congue eu. Justo nec ultrices dui sapien eget mi. Sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis. Risus pretium quam vulputate dignissim suspendisse in est ante in. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Ipsum consequat nisl vel pretium lectus quam id leo. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Purus gravida quis blandit turpis cursus in hac habitasse. Amet mattis vulputate enim nulla aliquet. Est ante in nibh mauris cursus mattis molestie. Cursus metus aliquam eleifend mi. Platea dictumst vestibulum rhoncus est pellentesque elit. Et malesuada fames ac turpis egestas. Euismod in pellentesque massa placerat duis. Sagittis orci a scelerisque purus semper eget duis at tellus. Felis donec et odio pellentesque diam volutpat commodo. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper.</p>
            </div>
        </div>
    )
}